---
title: "Smoking Rates Paper"
author: "Hunter Huckabay and Ivy Gates"
format: html
---

# Introduction
According to the American Lung Association, cigarette smoking rates have fallen significantly for both adults and youth since the 1990s. Since 2002, there have been more former smokers than current smokers and more than half of cigarette smokers have quit. However, the National Institute of Health has found that the rate of e-cigarette use has increased from 1.5% in 2011 to 20.8% in 2018. Our goal of this project is to compare cigarette use to e-cigarette use in America. We aim to see age groups smoke the most as the health repercussions smokers face. We aim to answer the question of how the rate of Americans smoking cigarettes has changed overtime and how the creation of e-cigarettes has impacted those rates. 

According to the CDC, more than 480,000 deaths annually are connected to smoking. It is important to understand the changes in smoking rates as it helps us understand how addiction to nicotine is changing shape and how it can tackled. It is also important to understand smoking rates in the United States as it helps us understand the new risks that might develop as smoking and e-cigarettes change overtime. While smoking in the United States as decreased over time due to the studies that have shown how dangerous it is, it is still important to understand how it has changed over time so we can understand how people are continuing to become addicted and who is the most impacted.