---
title: "Teen access 1"
author: "Ivy"
format: html
editor_options: 
  chunk_output_type: console
---

```{r}

# Purpose: Acquire, simulate and analyze data of teen access to tobacco products over the past 50 years and the repruccisons for selling these products to those under the MLSA
# MLSA - Minumum Legal Sales Age. 
# Author: Ivy Gates
# Email: gatesiv0@sewanee.edu
# Date: 13 February 2024

```

```{r}
#| include: FALSE 
##workspacesetup## 

library(tidyverse)
library(lubridate)
library(janitor)
library(RColorBrewer)

```

```{r}
 states<-
  read_csv(
    file = "https://raw.githubusercontent.com/mbrudd/nih_funding/refs/heads/main/state_populations.csv"
    ) |>
  select(State) |> 
  pull(State)

```

```{r}
simulated_data <-
  tibble( 
    state= 
      rep(states, 34),
    MLSA= 
      sample(18:21, 51*34, replace = TRUE),
    Year= 
      rep(c(1992:2025), 51),
    Level_of_offense= sample( c("felony", "misdemeanor"), 51*34, replace = TRUE )
     )
  
```

make simulated_data into bar graph containing State, MLSA, Year, and level of offense

```{r}
#make a bar chart
ggplot( simulated_data |> group_by(Year, Level_of_offense) |> tally() ) +
  geom_line( aes( x = Year, y = n, color = Level_of_offense )) + 
  geom_point( aes( x = Year, y = n, color = Level_of_offense ) ) +
  scale_color_manual( values = c("red","blue") ) +
  facet_wrap(~Level_of_offense) +
  expand_limits(y = 0) +
  labs( x = "Year",
        y = "Number of states" ) +
  theme_bw() +
  theme( legend.position = "none")
```

READ DATA #ADD CSV \`\`\`{r}

```{r}
#### Read in the data ####

MLSA <- read_csv(file = "Restrictions on Sales to Underage Persons_ States with Laws Prohibiting Sales of E-Cigarettes to Underage Persons (Enacted as of June 30, 2024 (n=58)).csv", show_col_types = FALSE)

new_mlsa <- read_csv("States and Territories with a Minimum Legal Sales Age (MLSA) of 21 Years for Purchasing Any Tobacco Product – Laws Enacted by September 30, 2024 (n=58).csv", show_col_types = F)

new_mlsa |> 
  group_by( ProvisionValue ) |>
  tally() |>
  ggplot( aes( x = ProvisionValue, y = n )) +
  geom_col()
```
